version: "3.8"

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
      - ./infra/nginx/certbot/conf:/etc/letsencrypt
      - ./infra/nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring
      - python

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./infra/nginx/certbot/conf:/etc/letsencrypt
      - ./infra/nginx/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d snacknews.site -d www.snacknews.site

  spring:
    build:
      context: ../../
      dockerfile: src/Dockerfile
    container_name: spring
    expose:
      - "8080"

  python:
    build:
      context: ../../
      dockerfile: python-nlp-service/Dockerfile
    container_name: python
    expose:
      - "5000"
