spring:
  jackson:
    time-zone: Asia/Seoul
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jwt:
    token:
      secretKey: umceightfightingjwttokenauthentication
      expiration:
        access: 14400000
        refresh: 1209600000

server:
  port: 8080

logging:
  level:
    root: info
    umc.snack.crawler.service.ArticleCrawlerService: info

gemini:
  baseurl: https://generativelanguage.googleapis.com/v1

googleai:
  api:
    key: ${GOOGLE_API_KEY}