spring:
  datasource:
    url: jdbc:mysql://${RDS_URL}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET_KEY}

google:
  api-key: ${GOOGLE_API_KEY}