name: CI (Only Crawl Quality)

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  crawl_quality_check:
    runs-on: ubuntu-latest
    env:
      SAMPLE_SIZE: "200"
      MAX_NULL_PERCENT: "20"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Run Crawl Quality Check (only 'live' tag)
        continue-on-error: true # 테스트 실패 시에도 CI는 성공으로 표시 (필요시 false로 변경)
        run: ./gradlew clean crawlQuality --no-daemon --stacktrace

