name: CI (crawl-quality)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build_and_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Run Build & Unit Tests (exclude 'live' tag)
        run: |
          chmod +x gradlew || true
          # [수정] build를 실행하되, @Tag("live")가 붙은 테스트는 제외
          ./gradlew clean build -Djunit.jupiter.tags.exclude=live --stacktrace

  crawl_quality_check:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      SAMPLE_SIZE: "200"
      MAX_NULL_PERCENT: "20"
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Run Crawl Quality Check (only 'live' tag)
        continue-on-error: true
        run: |
          chmod +x gradlew || true
          ./gradlew test -Djunit.jupiter.tags.include=live \
            -Dcrawl.sample=${SAMPLE_SIZE} \
            -Dcrawl.maxNullPercent=${MAX_NULL_PERCENT} \
            --stacktrace