name: CI (Only Crawl Quality)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  crawl_quality_check:
    runs-on: ubuntu-latest
    env:
      SAMPLE_SIZE: "200"
      MAX_NULL_PERCENT: "20"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Gradle wrapper perms
        run: chmod +x gradlew || true

      - name: Run Crawl Quality (task=crawlQuality, profile=test)
        run: |
          ./gradlew clean crawlQuality \
            -Dspring.profiles.active=test \
            -DJWT_SECRET_KEY=test-secret \
            -Dspring.sql.init.mode=never \
            -Dcrawl.sample=${SAMPLE_SIZE} \
            -Dcrawl.maxNullPercent=${MAX_NULL_PERCENT} \
            --no-daemon --stacktrace

      # junit XML
      - name: Upload test XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-xml-crawlQuality
          path: build/test-results/crawlQuality

      # html report
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-crawlQuality
          path: build/reports/tests/crawlQuality

      - name: Upload Gradle problems report (best-effort)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-problems-report
          path: |
            build/reports/problems/problems-report.html
            **/reports/problems/problems-report.html
          if-no-files-found: ignore