name: CI (Only Crawl Quality)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  crawl_quality_check:
    runs-on: ubuntu-latest
    env:
      SAMPLE_SIZE: "200"
      MAX_NULL_PERCENT: "20"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Run Crawl Quality Check (only 'live' tag)
        continue-on-error: true
        run: |
          chmod +x gradlew || true
          # 시스템 프로퍼티(-D)로 플레이스홀더 값 임시 지정
          ./gradlew test -Djunit.jupiter.tags.include=live \
            -Dcrawl.sample=${SAMPLE_SIZE} \
            -Dcrawl.maxNullPercent=${MAX_NULL_PERCENT} \
            -DMYSQL_HOST=ignore-me \
            -DMYSQL_PORT=3308 \
            -DMYSQL_DATABASE=ignore-me \
            -DMYSQL_USER=ignore-me \
            -DMYSQL_PASSWORD=ignore-me \
            -DFASTAPI_URL=http://ignore-me \
            --stacktrace