name: CI (Only Crawl Quality)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  crawl_quality_check:
    runs-on: ubuntu-latest
    env:
      SAMPLE_SIZE: "200"
      MAX_NULL_PERCENT: "20"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Gradle wrapper perms
        run: chmod +x gradlew || true

      - name: Run Crawl Quality Check (@Tag=live, profile=test)
        run: |
          ./gradlew clean test \
            -Dspring.profiles.active=test \
            -Dspring.config.import= \
            -Djunit.jupiter.tags.include=live \
            -Dcrawl.sample=${SAMPLE_SIZE} \
            -Dcrawl.maxNullPercent=${MAX_NULL_PERCENT} \
            --no-daemon --stacktrace --info --fail-fast

      - name: Upload test report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Upload raw test results (XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-xml
          path: build/test-results/test