name: CI (Only Crawl Quality)

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  crawl_quality_check:
    runs-on: ubuntu-latest
    env:
      SAMPLE_SIZE: "200"
      MAX_NULL_PERCENT: "20"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Run Crawl Quality Check (only 'live' tag)
        run: |
          ./gradlew test --tests "umc.snack.crawler.CrawlQualityTest" 
            -Dspring.profiles.active=test
            -Dcrawl.sample=${SAMPLE_SIZE} \
            -Dcrawl.maxNullPercent=${MAX_NULL_PERCENT} \
            -DJWT_SECRET_KEY=test-secret \
            --no-daemon --stacktrace

