name: CI (Only Crawl Quality)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  crawl_quality_check:
    runs-on: ubuntu-latest
    env:
      SAMPLE_SIZE: "200"
      MAX_NULL_PERCENT: "20"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Gradle wrapper perms
        run: chmod +x gradlew

      - name: Run Crawl Quality
        run: |
          ./gradlew clean crawlQuality \
            -Dspring.profiles.active=test \
            -Djunit.jupiter.tags.include=live \
            -Dcrawl.sample=${SAMPLE_SIZE} \
            -Dcrawl.maxNullPercent=${MAX_NULL_PERCENT} \
            --no-daemon --stacktrace --info

      - name: Upload test report (crawlQuality task)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crawl-quality-report
          path: build/reports/tests/crawlQuality

      - name: Upload problems report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-problems-report
          path: build/reports/problems/problems-report.html