#deploy.yml

- name: Build jar on GitHub
  run: ./gradlew clean build -x test

- name: Upload jar to EC2
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
    source: build/libs/*.jar
    target: /home/ubuntu/snack/build/libs/

- name: Restart EC2 Service
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
    script: |
      sudo systemctl restart snack.service
