name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload source code to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: |
            ./src
            ./infra
            ./docker-compose.yml
            ./build.gradle
            ./settings.gradle
            ./gradlew
            ./gradle
          target: /home/ubuntu/Back-end

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Moving to project directory"
            cd /home/ubuntu/Back-end

            echo "Clean and build project"
            ./gradlew clean build -x test

            echo "Stopping existing containers"
            docker-compose down

            echo "🔨 Building and starting containers"
            docker-compose up -d --build

            echo "Checking status"
            docker ps
